#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6450518497                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.hjiangsu.thunder&hl=en_US
# presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : An open-source cross-platform Lemmy client for iOS and Android built with Flutter

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Emil Baehr                                
your_link                                 : https://emilbaehr.com                     
your_city                                 : Copenhagen                                
email_address                             : emil.baehr@gmail.com
facebook_username                         :                                           
instagram_username                        : ebaehr
twitter_username                          : ebaehr
github_username                           : emilbaehr
youtube_username                          :
mastodon_link                             : https://mastodon.social/@ebaehr



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : üè° Communities & Users
    description                           : "- Browse general feeds (All / Local / Subscribed)
                                            - View, subscribe, favorite, and block communities
                                            - View user posts/comments, and block unwanted users"
    fontawesome_icon_name                 : magic
    
  - title                                 : üåé Instances
    description                           : "- View instance information and version
                                            - Block unwanted instances (on supported instances)"
    fontawesome_icon_name                 : mobile

  - title                                 : üîé Search
    description                           : "- Show trending communities on the current instance
                                            - Search for communities, users, posts and comments
                                            - Apply advanced search filters (sort, feed, community, creator)"
    fontawesome_icon_name                 : play-circle

  - title                                 : üóíÔ∏è Posts & Comments
    description                           : "- Create and edit posts and comments
                                            - Vote, save, and share posts and comments
                                            - Customize swipe actions for posts and comments
                                            - Filter posts based on keywords"
    fontawesome_icon_name                 : sync

  - title                                 : üîë Accounts
    description                           : "- View profile information (posts/comments/saved)
                                            - View notifications including replies, mentions, and private messages
                                            - Synced account settings (show read posts, comment scores, bot accounts)
                                            - Support for multiple accounts, and guest accounts on different instances"
    fontawesome_icon_name                 : adjust
  
  - title                                 : üé® Customization
    description                           : "- Support for Material You theming (on applicable devices)
                                            - Support for light/dark/OLED/system mode, and preset accent colors
                                            - Custom font scaling of content
                                            - Customize and preview post/comment appearance (compact/card)"
    fontawesome_icon_name                 : star

  - title                                 : üéâ Extras
    description                           : "- Import and export app settings
                                            - In-app update notifications for new GitHub releases
                                            - Language support via community translations (Weblate)"
    fontawesome_icon_name                 : arrow-alt-circle-down
  
  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

# cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
# cover_overlay_color                       : "#363b3d"
# cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
